export const ADMIN_API_ROUTES={
    DASHBOARD:{
        GET:(filter:string)=>`/admin/dashboard?filter=${filter}`,
        BEST_SELLING_PRODUCTS:'/admin/best-selling-products',
        BEST_SELLING_CATEGORIES:'/admin/best-selling-categories'
    },
    CATEGORIES_MANAGEMENT:{
       EDIT_CATEGORY:'/admin/categories',
       DELETE_CATEGORY:(categoryId:string)=>`/admin/categories/${categoryId}`,
       GET:'/admin/categories',
       UPLOAD_CATEGORY:'/admin/upload-category'
    },
    PRODUCTS_MANAGEMENT:{
      GET_ALL:"/admin/products",
      SEARCH_PRODUCTS:'/admin/search-products',
      DELETE_PRODUCT:(productId:string)=>`/admin/products/${productId}`,
      GET_BY_ID:(productId:string)=>`/admin/products/${productId}`,
      UPDATE_PRODUCT:(productId:string)=>`/admin/products/${productId}`,
      CREATE_PRODUCT:"/admin/products"
    },
    USERS_MANAGEMENT:{
       GET:'/admin/customers',
       UPDATE_STATUS:'/admin/statusUpdate',
       SEARCH_USER:"/admin/search-user"
    },
    ORDERS_MANAGEMENT:{
     HANDLE_ORDER_STATUS:"/admin/orders",
     GET_ALL:"/admin/orders"
    },
    AUTH:{
      LOGIN:'/admin/login'
    },
    OFFERS_MANAGEMENT:{
        UPDATE_PRODUCT_OFFER:'/admin/product-offer',
        UPDATE_CATEGORY_OFFER:'/admin/category-offer',
        GET_ALL:"/admin/offers"
    },
    COUPONS_MANAGEMENT:{
        REMOVE:(couponId:string)=>`/admin/coupon/${couponId}`,
        CREATE:'/admin/coupon',
        GET:'/admin/coupon'
    },
    SALES_REPORT:{
        GET_ALL:'/admin/sales-report',
        GENERATE:'/admin/sales-report'
    }
}